version: '3.2'

services:
  database:
    image: postgres:13.3-alpine3.14
    environment:
      - POSTGRES_DB=${PSQGL_DATABASE_NAME}
      - POSTGRES_USER=${PSQGL_DATABASE_USER}
      - POSTGRES_PASSWORD=${PSQGL_DATABASE_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
    networks:
      - billabear

  php-fpm:
    image: billabear/backend:latest
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=pgsql://${PSQGL_DATABASE_USER}:${PSQGL_DATABASE_PASSWORD}@database:5432/${PSQGL_DATABASE_NAME}
      - STRIPE_PRIVATE_API_KEY=${STRIPE_PRIVATE_API_KEY}
      - STRIPE_PUBLIC_API_KEY=${STRIPE_PUBLIC_API_KEY}
    networks:
      - billabear

  worker:
    image: billabear/backend:latest
    command: ["bin/console messenger:consume scheduler_main main"]
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - STRIPE_PRIVATE_API_KEY=${STRIPE_PRIVATE_API_KEY}
      - STRIPE_PUBLIC_API_KEY=${STRIPE_PUBLIC_API_KEY}
      - DATABASE_URL=pgsql://${PSQGL_DATABASE_USER}:${PSQGL_DATABASE_PASSWORD}@database:5432/${PSQGL_DATABASE_NAME}
    networks:
      - billabear

  nginx:
    image: billabear/frontend:latest
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - billabear

networks:
  billabear:
    driver: bridge
